version: '3.5'

services:

  webapp:
    build: 
      context: ./client
      dockerfile: DockerFile
    ports:
      - "5555:80"

  server:
    build: 
      context: ./server
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - dataset
      - database
    environment: 
      SERVICE: database
      
  database:
    image: mongo

  dataset:
    build: 
      context: ./data_setup
      dockerfile: DockerFile
    depends_on:
      - database
    environment: 
      SERVICE: database